/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGoogleRouteImport } from './routes/api/google'
import { Route as ApiJrRouteImport } from './routes/api/jr'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiPartyRouteImport } from './routes/api/party'
import { Route as ApiQuakeRouteImport } from './routes/api/quake'
import { Route as ApiRadarRouteImport } from './routes/api/radar'
import { Route as ApiReserveRouteImport } from './routes/api/reserve'
import { Route as ApiRoadsRouteImport } from './routes/api/roads'
import { Route as ApiSaveRouteImport } from './routes/api/save'
import { Route as ApiTransitRouteImport } from './routes/api/transit'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiKonbiniChatRouteImport } from './routes/api/konbini/chat'
import { Route as ApiKonbiniStoresRouteImport } from './routes/api/konbini/stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleRoute = ApiGoogleRouteImport.update({
  id: '/api/google',
  path: '/api/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJrRoute = ApiJrRouteImport.update({
  id: '/api/jr',
  path: '/api/jr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartyRoute = ApiPartyRouteImport.update({
  id: '/api/party',
  path: '/api/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuakeRoute = ApiQuakeRouteImport.update({
  id: '/api/quake',
  path: '/api/quake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReserveRoute = ApiReserveRouteImport.update({
  id: '/api/reserve',
  path: '/api/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadsRoute = ApiRoadsRouteImport.update({
  id: '/api/roads',
  path: '/api/roads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveRoute = ApiSaveRouteImport.update({
  id: '/api/save',
  path: '/api/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransitRoute = ApiTransitRouteImport.update({
  id: '/api/transit',
  path: '/api/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKonbiniChatRoute = ApiKonbiniChatRouteImport.update({
  id: '/api/konbini/chat',
  path: '/api/konbini/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKonbiniStoresRoute = ApiKonbiniStoresRouteImport.update({
  id: '/api/konbini/stores',
  path: '/api/konbini/stores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/jr': typeof ApiJrRoute
  '/api/live': typeof ApiLiveRoute
  '/api/party': typeof ApiPartyRoute
  '/api/quake': typeof ApiQuakeRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/reserve': typeof ApiReserveRoute
  '/api/roads': typeof ApiRoadsRoute
  '/api/save': typeof ApiSaveRoute
  '/api/transit': typeof ApiTransitRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/konbini/chat': typeof ApiKonbiniChatRoute
  '/api/konbini/stores': typeof ApiKonbiniStoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/jr': typeof ApiJrRoute
  '/api/live': typeof ApiLiveRoute
  '/api/party': typeof ApiPartyRoute
  '/api/quake': typeof ApiQuakeRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/reserve': typeof ApiReserveRoute
  '/api/roads': typeof ApiRoadsRoute
  '/api/save': typeof ApiSaveRoute
  '/api/transit': typeof ApiTransitRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/konbini/chat': typeof ApiKonbiniChatRoute
  '/api/konbini/stores': typeof ApiKonbiniStoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/jr': typeof ApiJrRoute
  '/api/live': typeof ApiLiveRoute
  '/api/party': typeof ApiPartyRoute
  '/api/quake': typeof ApiQuakeRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/reserve': typeof ApiReserveRoute
  '/api/roads': typeof ApiRoadsRoute
  '/api/save': typeof ApiSaveRoute
  '/api/transit': typeof ApiTransitRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/konbini/chat': typeof ApiKonbiniChatRoute
  '/api/konbini/stores': typeof ApiKonbiniStoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/google'
    | '/api/jr'
    | '/api/live'
    | '/api/party'
    | '/api/quake'
    | '/api/radar'
    | '/api/reserve'
    | '/api/roads'
    | '/api/save'
    | '/api/transit'
    | '/api/weather'
    | '/api/konbini/chat'
    | '/api/konbini/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/google'
    | '/api/jr'
    | '/api/live'
    | '/api/party'
    | '/api/quake'
    | '/api/radar'
    | '/api/reserve'
    | '/api/roads'
    | '/api/save'
    | '/api/transit'
    | '/api/weather'
    | '/api/konbini/chat'
    | '/api/konbini/stores'
  id:
    | '__root__'
    | '/'
    | '/api/google'
    | '/api/jr'
    | '/api/live'
    | '/api/party'
    | '/api/quake'
    | '/api/radar'
    | '/api/reserve'
    | '/api/roads'
    | '/api/save'
    | '/api/transit'
    | '/api/weather'
    | '/api/konbini/chat'
    | '/api/konbini/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGoogleRoute: typeof ApiGoogleRoute
  ApiJrRoute: typeof ApiJrRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiPartyRoute: typeof ApiPartyRoute
  ApiQuakeRoute: typeof ApiQuakeRoute
  ApiRadarRoute: typeof ApiRadarRoute
  ApiReserveRoute: typeof ApiReserveRoute
  ApiRoadsRoute: typeof ApiRoadsRoute
  ApiSaveRoute: typeof ApiSaveRoute
  ApiTransitRoute: typeof ApiTransitRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ApiKonbiniChatRoute: typeof ApiKonbiniChatRoute
  ApiKonbiniStoresRoute: typeof ApiKonbiniStoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google': {
      id: '/api/google'
      path: '/api/google'
      fullPath: '/api/google'
      preLoaderRoute: typeof ApiGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jr': {
      id: '/api/jr'
      path: '/api/jr'
      fullPath: '/api/jr'
      preLoaderRoute: typeof ApiJrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/party': {
      id: '/api/party'
      path: '/api/party'
      fullPath: '/api/party'
      preLoaderRoute: typeof ApiPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quake': {
      id: '/api/quake'
      path: '/api/quake'
      fullPath: '/api/quake'
      preLoaderRoute: typeof ApiQuakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reserve': {
      id: '/api/reserve'
      path: '/api/reserve'
      fullPath: '/api/reserve'
      preLoaderRoute: typeof ApiReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roads': {
      id: '/api/roads'
      path: '/api/roads'
      fullPath: '/api/roads'
      preLoaderRoute: typeof ApiRoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save': {
      id: '/api/save'
      path: '/api/save'
      fullPath: '/api/save'
      preLoaderRoute: typeof ApiSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transit': {
      id: '/api/transit'
      path: '/api/transit'
      fullPath: '/api/transit'
      preLoaderRoute: typeof ApiTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/konbini/chat': {
      id: '/api/konbini/chat'
      path: '/api/konbini/chat'
      fullPath: '/api/konbini/chat'
      preLoaderRoute: typeof ApiKonbiniChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/konbini/stores': {
      id: '/api/konbini/stores'
      path: '/api/konbini/stores'
      fullPath: '/api/konbini/stores'
      preLoaderRoute: typeof ApiKonbiniStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGoogleRoute: ApiGoogleRoute,
  ApiJrRoute: ApiJrRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiPartyRoute: ApiPartyRoute,
  ApiQuakeRoute: ApiQuakeRoute,
  ApiRadarRoute: ApiRadarRoute,
  ApiReserveRoute: ApiReserveRoute,
  ApiRoadsRoute: ApiRoadsRoute,
  ApiSaveRoute: ApiSaveRoute,
  ApiTransitRoute: ApiTransitRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ApiKonbiniChatRoute: ApiKonbiniChatRoute,
  ApiKonbiniStoresRoute: ApiKonbiniStoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
